# This runs the linter (cppcheck) and
# compiles Raging MIDI.
language: cpp
compiler: gcc
before_install:
 - sudo apt-get update -qq
 - sudo apt-get install -qq libqt4-dev libasound2-dev cppcheck
 - cd src
script:
 - cppcheck --enable=all --error-exitcode=1 .
 - qmake .
 - make
