sudo: false
language: cpp
compiler: clang
addons:
  apt:
    packages:
    - libqt4-dev
    - libasound2-dev
install:
 - git submodule update --init
 - cd src
script:
 - qmake -spec unsupported/linux-clang .
 - make
